### ISSUE TITLE
All of the SDA1 Nets Have Been Renamed to SCL1

### ISSUE THREAD

**Issue by Mikefly123** [proveskit/antenna-board#6]
This is really annoying, not sure why this happened! We might have to reroute everything: 

<img width="1140" alt="Screenshot 2024-06-19 at 5 09 58 PM" src="https://github.com/proveskit/antenna-board/assets/61564344/226d8a8c-bec7-46e1-b3fb-181c78a09c62">

**Comment by Mikefly123** [comment]
# Hotfix 

Hotfixed by renaming the nets from SCL to SDA. This appears to have corrected everything. We need to make sure to verify all the connections before shipping! 

<img width="1207" alt="Screenshot 2024-06-19 at 5 15 19 PM" src="https://github.com/proveskit/antenna-board/assets/61564344/4b6d2cc7-a0f6-448a-9b98-332f8ad508f2">

**Comment by NicoleMaggard** [comment]
Before:
![image](https://github.com/proveskit/antenna-board/assets/109390242/f754b9f2-2f08-4e22-82d5-44fcce611b55)
After:
![image](https://github.com/proveskit/antenna-board/assets/109390242/c08cf994-4678-458b-8407-0652e647dd96)

**Comment by Mikefly123** [comment]
We did it!
